UmbracoMandatory/ViewModels/ContactForm.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace UmbracoMandatory.ViewModels
{
    public class ContactForm
    {
        [Required]
        public string Name { get; set; }

        [Required]
        [EmailAddress(ErrorMessage ="This is not a valid email")]
        public string Email { get; set; }

        [Required]
        public string Subject { get; set; }

        [Required]
        public string Message { get; set; }
    }
}

UmbracoMandatory/Controllers/ContactFormSurfaceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Umbraco.Core.Models;
using Umbraco.Web.Mvc;
using UmbracoMandatory.ViewModels;

namespace UmbracoMandatory.Controllers
{
    public class ContactFormSurfaceController : SurfaceController
    {
        // GET: ContactFormSurface
        public ActionResult Index()
        {
            return PartialView("ContactForm", new ContactForm());
        }

    }
}

UmbracoMandatory/Controllers/HandleFormSubmitController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using Umbraco.Web.Mvc;
using UmbracoMandatory.ViewModels;
using Umbraco.Core.Models;

namespace UmbracoMandatory.Controllers
{
    public class HandleFormSubmitController : SurfaceController
    {
        // GET: HandleFormSubmit
        [HttpPost]
        public ActionResult HandleFormSubmit(ContactForm model)
        {

            if (!ModelState.IsValid) { return CurrentUmbracoPage(); }

            IContent message = Services.ContentService.CreateContent(model.Subject, CurrentPage.Id, "Message");
            message.SetValue("name", model.Name);
            message.SetValue("email", model.Email);
            message.SetValue("subject", model.Subject);
            message.SetValue("message", model.Message);

            Services.ContentService.Save(message);
            TempData["success"] = true;

            /*
            MailMessage message = new MailMessage();
            message.To.Add("henrikbj1990@hotmail.com");
            message.Subject = model.Subject;
            message.From = new MailAddress(model.Email, model.Name);
            message.Body = model.Message;
            using (SmtpClient smtp = new SmtpClient())
            {
                smtp.DeliveryMethod = SmtpDeliveryMethod.Network;
                smtp.UseDefaultCredentials = false;
                smtp.EnableSsl = true;
                smtp.Host = "smtp.gmail.com";
                smtp.Port = 587;
                smtp.Credentials = new System.Net.NetworkCredential("henrikbj1990@gmail.com", "nope");
                smtp.EnableSsl = true;
                // send mail
                smtp.Send(message);
                TempData["success"] = true;
            }*/


            return RedirectToCurrentUmbracoPage();
        }
    }
}

UmbracoMandatory/Views/About.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "Master.cshtml";
}
@CurrentPage.GetGridHtml("aboutGrid")

UmbracoMandatory/Views/ArticlesItem.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "Master.cshtml";
}
<h1>@Umbraco.Field("articleTitle")</h1>
<p>@Umbraco.Field("articleContents")</p>

UmbracoMandatory/Views/ArticlesMain.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "Master.cshtml";
}

<h1>@Umbraco.Field("pageName")</h1>
	
	<p>List of articles:</p>
		<ul>
		@foreach(var articleItem in CurrentPage.Children)
		{
			<li><a href="@articleItem.Url">@articleItem.Name</a></li>	
		}

	</ul>
<p>@Umbraco.Field("articlesBodyText")</p>

UmbracoMandatory/Views/ContactPage.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "Master.cshtml";
}
<h1>@CurrentPage.Name</h1>
<div>
	@Html.Action("Index", "ContactFormSurface")
</div>

UmbracoMandatory/Views/HomePage.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "Master.cshtml";
}
@{ var newProjects = @Umbraco.Content(1069).Children().Where(("projectStatus.Contains(\"9\")")).OrderBy("CreateDate desc").Take(3);}

<h1>@Umbraco.Field("siteTitle")</h1>
	<p>@Umbraco.Field("mainContent")</p>
<br>
	<h4>Here is 3 recently completed projects:</h4>
	@foreach(var item in newProjects){
		<div class="col-md-4">
            <div class="well well-sm">
					<a href="@item.Url">
						<h4>@item.Name</h4>
						<p>Created: @item.CreateDate.ToString("MM/dd-yyyy")</p>
					</a>
			</div>
        </div>
}
	
	

UmbracoMandatory/Views/Login.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "Master.cshtml";
}
@Umbraco.RenderMacro("Login")

UmbracoMandatory/Views/MacroPartials/ContactForm.cshtml
@model UmbracoMandatory.ViewModels.ContactForm
    @{ 
        Layout = null;
    }
@if (TempData["success"] == null)
{
    using (Html.BeginUmbracoForm("HandleFormSubmit", "HandleFormSubmit", new object { },
    new { @class = "form-horizontal" }))
    {
        <div class="form-group">
            @Html.LabelFor(m => m.Name, new { @class = "col-sm-2 control-label" })
            <div class="col-sm-6">
                @Html.TextBoxFor(m => m.Name, new { @class = "form-control", placeholder = "Name" })
                @Html.ValidationMessageFor(m => m.Name)
            </div>
        </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Email, new { @class = "col-sm-2 control-label" })
        <div class="col-sm-6">
            @Html.TextBoxFor(m => m.Email, new { @class = "form-control", placeholder = "Email address" })
            @Html.ValidationMessageFor(m => m.Email)
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Subject, new { @class = "col-sm-2 control-label" })
        <div class="col-sm-6">
            @Html.TextBoxFor(m => m.Subject, new { @class = "form-control", placeholder = "Subject" })
            @Html.ValidationMessageFor(m => m.Subject)
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Message, new { @class = "col-sm-2 control-label" })
        <div class="col-sm-6">
            @Html.TextAreaFor(m => m.Message, new { @class = "form-control", placeholder = "Your message" })
            @Html.ValidationMessageFor(m => m.Message)
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-6">
            <button id="contact-submit" type="submit" class="btn btn-primary input-medium pullleft">Send</button>
        </div>
    </div>

    }
}
else
{
    <p>Thank you for contacting us. We’ll be in touch soon!</p>
}

UmbracoMandatory/Views/MacroPartials/Login.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage


@using System.Web.Mvc.Html
@using ClientDependency.Core.Mvc
@using Umbraco.Web
@using Umbraco.Web.Models
@using Umbraco.Web.Controllers

@{
    var loginModel = new LoginModel();
    }

@if (!Members.GetCurrentLoginStatus().IsLoggedIn)
{
    using (Html.BeginUmbracoForm<UmbLoginController>
        ("HandleLogin"))
    {
<div class="col-lg-4">
        <h2 class="form-signin-heading">Login</h2>
			
        @Html.ValidationSummary("loginModel", true)

			
        <div class="form-group">
            @Html.LabelFor(m => loginModel.Username, new { @class = "control-label" })
            
                @Html.TextBoxFor(m => loginModel.Username, new
           {
               @class = "form-control",
               placeholder = "Username"
           })
                @Html.ValidationMessageFor(m => loginModel.Username)
        </div>
        <div class="form-group">
            @Html.LabelFor(m => loginModel.Password, new { @class = "control-label" })
            
                @Html.PasswordFor(m => loginModel.Password, new
           {
               @class = "form-control",
               placeholder = "Password"
           })
                @Html.ValidationMessageFor(m => loginModel.Password)
            
        </div>
        <br />
                <button class="btn btn-lg btn-primary btn-block">Login</button>
					</div>
    }
}

else
{
	<h1>Logged in!</h1>
            <p>You are currently logged in as @Members.GetCurrentLoginStatus().Name</p>
            var logoutModel = new PostRedirectModel();
            logoutModel.RedirectUrl = "/";
            using (Html.BeginUmbracoForm<UmbLoginStatusController>
                ("HandleLogout"))
                {
                <button class="btn btn-primary input-medium pullleft">Logout</button>
                @Html.HiddenFor(m => logoutModel.RedirectUrl)
                }
                }

UmbracoMandatory/Views/MacroPartials/LoginForm1.cshtml
@using System.Web.Mvc.Html
@using ClientDependency.Core.Mvc
@using Umbraco.Web
@using Umbraco.Web.Models
@using Umbraco.Web.Controllers

@{
    var loginModel = new LoginModel();
}

    @if (!Members.GetCurrentLoginStatus().IsLoggedIn) {
    using (Html.BeginUmbracoForm<UmbLoginController>
        ("HandleLogin"))
        {
        <fieldset>
            <legend>Login</legend>

            @Html.ValidationSummary("loginModel", true)

            @Html.LabelFor(m => loginModel.Username)
            @Html.TextBoxFor(m => loginModel.Username)
            @Html.ValidationMessageFor(m => loginModel.Username)
            <br />
            @Html.LabelFor(m => loginModel.Password)
            @Html.PasswordFor(m => loginModel.Password)
            @Html.ValidationMessageFor(m => loginModel.Password)
            <br />
            <button>Login</button>
        </fieldset>
        }
        }
        else {
        <p>
            You are currently logged in as
            @Members.GetCurrentLoginStatus().Name
        </p>
        var logoutModel = new PostRedirectModel();
        logoutModel.RedirectUrl = "/";
        using (Html.BeginUmbracoForm<UmbLoginStatusController>
            ("HandleLogout")) {
            <button>Logout</button>
            @Html.HiddenFor(m => logoutModel.RedirectUrl)
            }
            }

UmbracoMandatory/Views/MacroPartials/MemberList.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage
@using Newtonsoft.Json;
@using Umbraco.Web.Models;
@{  var memberService = ApplicationContext.Current.Services.MemberService;
    var members = memberService.GetMembersByGroup("Active");
    }

<h3>Active Users:</h3>
<div>
    @foreach (var member in members)
    {
        String[] skills = member.GetValue("skills").ToString().Split(',');
        string skillString = String.Join(", ", from skill in skills select umbraco.library.GetPreValueAsString(Convert.ToInt32(skill)));
        <div>
            @if (member.GetValue("photo") != null)
            {
                string image = member.GetValue<string>("photo");
                ImageCropDataSet imageCrop = JsonConvert.DeserializeObject<ImageCropDataSet>(image);
                string imagePath = imageCrop.Src.GetCropUrl("profile");
                <img src="@imagePath "/> <br />
            }
            @member.GetValue("firstname")
            @member.GetValue("lastname")
            <br>
            @member.GetValue("address")
            <br>
            @member.GetValue("zip")
            @member.GetValue("city")
            <br>
            Email: @member.Email
            <br>
            Skills: @skillString
        </div>
				<br />
    }
</div>
<h3>Prospect users:</h3>
@{ var prospects = memberService.GetMembersByGroup("Prospect");}

@foreach (var prospect in prospects)
{
    <div>
        @prospect.Name
        <br />
        Email: @prospect.Email
    </div>
}

UmbracoMandatory/Views/MacroPartials/mainMenu.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage


@{ var root = CurrentPage.AncestorOrSelf(1); }
	<ul class="nav navbar-nav">
		<li class="@((CurrentPage.Name == root.Name) ? "active" : null)">
			<a href="/">@root.Name</a>
		</li>
		@foreach (var menuItem in root.Children.Where("Visible")) {
			<li class="@(menuItem.IsAncestorOrSelf(CurrentPage) ? "active" : null)">
				<a href="@menuItem.Url">@menuItem.Name</a>
			</li>
		}
</ul>

	
	

UmbracoMandatory/Views/MacroPartials/sitemap.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage


@*
    This snippet makes a list of links of all visible pages of the site, as nested unordered html lists.

    How it works:
    - It uses a custom Razor helper called Traverse() to select and display the markup and links.
*@

@{ var selection = CurrentPage.Site(); }

<div class="sitemap">
    @* Render the sitemap by passing the root node to the traverse helper, below *@
    @Traverse(selection)
</div>


@* Helper method to travers through all descendants *@
@helper Traverse(dynamic node)
{
    @* Update the level to reflect how deep you want the sitemap to go *@
    var maxLevelForSitemap = 4;

    @* Select visible children *@
    var selection = node.Children.Where("Level <= " + maxLevelForSitemap);

    @* If any items are returned, render a list *@
    if (selection.Any())
    {
        <ul>
            @foreach (var item in selection)
            {
                <li class="level-@item.Level">
                    <a href="@item.Url">@item.Name</a>

                    @* Run the traverse helper again for any child pages *@
                    @Traverse(item)
                </li>
            }
        </ul>
    }
}

UmbracoMandatory/Views/Master.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = null;
}
@{ var root = CurrentPage.AncestorOrSelf(1); }
@{ var articles = @Umbraco.Content(1065);}
@{ var projects = @Umbraco.Content(1069);}
<!doctype html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@Umbraco.Field("pageName")</title>
    <meta name="description" content="@Umbraco.Field("metaDescription")">
    <meta name="keywords" content="@Umbraco.Field("metaKeywords")">
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <link rel="stylesheet" href="~/css/style.css">
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
</head>
<body>
    <div id="wrapper">
        <nav class="navbar navbar-default">
            <div class="container">
                <div class="navbar-header">
                    <a class="navbar-brand" href="/">Aarhus Web Dev Corp</a>
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        @foreach (var menuItem in root.Children.Where("Visible").OrderBy("CreateDate desc"))
                        {
                            var isProtected = umbraco.library.IsProtected(menuItem.id, menuItem.path);
                            var loginAccess = umbraco.library.IsProtected(menuItem.id, menuItem.path) && umbraco.library.HasAccess(menuItem.id, menuItem.path);

                            if (!isProtected || loginAccess)
                            {

                                <li class="@(menuItem.IsAncestorOrSelf(CurrentPage) ? " active" : null)">
                                    <a href="@menuItem.Url">@menuItem.Name</a>
                                </li>
                            }
                        }
                        <li class="dropdown">
                            <a href="/articles" class="dropdown-toggle" onclick="window.location.href='/articles'" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Articles<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                @{
                                    var Articles = CurrentPage.Site().FirstChild("ArticlesMain").Children.Where("Visible").OrderBy("Name");
                                }
                                @foreach (var item in Articles)
                                {
                                    <li>
                                        <a href="@item.Url">@item.Name</a>
                                    </li>
                                }
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="/projects" class="dropdown-toggle" onclick="window.location.href='/projects'" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Projects<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                @{
                                    var Projects = CurrentPage.Site().FirstChild("ProjectsMain").Children.Where("Visible").OrderBy("Name");
                                }
                                @foreach (var children in Projects)
                                {
                                    var isChildProtected = umbraco.library.IsProtected(children.Id, children.path);
                                    var loginChildAccess = umbraco.library.IsProtected(children.id, children.path) && umbraco.library.HasAccess(children.id, children.path);
                                    if (!isChildProtected || loginChildAccess)
                                    {
                                        <li>   <a href="@children.Url">@children.Name</a></li>
                                    }
                                }
                            </ul>
                        </li>
                        <li>
                            @if (Members.GetCurrentLoginStatus().IsLoggedIn)
                            {
                                <a class="pull-right" href="/login">@Members.GetCurrentLoginStatus().Name</a>
                            }
                            else
                            {
                                <a class="right" href="/login">Login</a>
                            }
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container content">
            @RenderBody()
        </div>
        <footer class="footer">
            <p class="text-muted">Aarhus Web Development Corporation © - 2016 </p>
        </footer>
    </div>
</body>

<script src="~/Scripts/jquery-2.2.0.min.js"></script>
<script src="~/Scripts/bootstrap.min.js"></script>
<script src="~/Scripts/scripts.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

UmbracoMandatory/Views/Members.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "Master.cshtml";
}
@using Newtonsoft.Json;
@using Umbraco.Web.Models;
@{  var memberService = ApplicationContext.Current.Services.MemberService;
    var members = memberService.GetMembersByGroup("Active");
    }

<h1>Members</h1>
<hr>
	<h3 style="clear:both";>Active Users:</h3>
		
@foreach (var member in members)
{
	<div class="member">
        <div class="col-md-2 profile">
            @if (member.GetValue("photo") != null)
            {
                string image = member.GetValue<string>("photo");
                ImageCropDataSet imageCrops = JsonConvert.DeserializeObject<ImageCropDataSet>(image);
                string imagePath = imageCrops.Src.GetCropUrl();
                <img src="@imagePath" style="height:100px;width:auto;" />
            }
        </div>
        <div class="col-md-4">
            <p>
                <h4>
                    @member.GetValue("firstname")
                    @member.GetValue("lastname")
                </h4>
                @member.GetValue("address")<br>
                @member.GetValue("zip") @member.GetValue("city") <br>
                Email: @member.Email<br>
                Skills:
                @{
                    String[] skills = member.GetValue("skills").ToString().Split(',');
                    string skillString =
                    string.Join(", ", from skill in skills
                                      select umbraco.library.GetPreValueAsString(Convert.ToInt32(skill)));
                    <span>@skillString</span>
                }
            </p>
    </div></div>
				<br>

                    }
 
<h3 style="clear:both">Prospect users:</h3>
@{ var prospects = memberService.GetMembersByGroup("Prospect");}

@foreach (var prospect in prospects)
{
    <div class="col-md-4" style="padding-bottom:5px">
        @prospect.Name
        <br />
        Email: @prospect.Email
    </div>
}

UmbracoMandatory/Views/Message.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = null;
}

UmbracoMandatory/Views/Partials/Grid/Bootstrap2.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates
@using Newtonsoft.Json.Linq

@* 
    Razor helpers located at the bottom of this file
*@

@if (Model != null && Model.sections != null)
{
    var oneColumn = ((System.Collections.ICollection)Model.sections).Count == 1;
    
    <div class="umb-grid">
        @if (oneColumn)
        {
            foreach (var section in Model.sections) {
                <div class="grid-section">
                    @foreach (var row in section.rows) {
                        @renderRow(row, true);
                    }
                </div>
            }   
        }else { 
            <div class="container">
                <div class="row clearfix">
                    @foreach (var s in Model.sections) {
                        <div class="grid-section">
                            <div class="@("span" + s.grid) column">
                                @foreach (var row in s.rows) {
                                    @renderRow(row, false);
                                }
                            </div>
                        </div>
                    }
                </div>
            </div>   
        }
    </div>
}

@helper renderRow(dynamic row, bool singleColumn){
    <div @RenderElementAttributes(row)>
        @Umbraco.If(singleColumn, "<div class='container'>")
        <div class="row clearfix">
            @foreach ( var area in row.areas ) {
            <div class="@("span" + area.grid) column">
                <div @RenderElementAttributes(area)>
                    @foreach (var control in area.controls) {
                        if (control !=null && control.editor != null && control.editor.view != null ) {
                            <text>@Html.Partial("grid/editors/base", (object)control)</text>
                        }
                    }
                </div>
            </div>}
        </div>
        @Umbraco.If(singleColumn, "</div>")
    </div>
}

@functions {
    public static MvcHtmlString RenderElementAttributes(dynamic contentItem)
    {
        var attrs = new List<string>();
        JObject cfg = contentItem.config;

        if(cfg != null)
            foreach (JProperty property in cfg.Properties()) {
                attrs.Add(property.Name + "=\"" + property.Value.ToString() + "\"");
            }
                
        JObject style = contentItem.styles;

        if (style != null) { 
        var cssVals = new List<string>();
        foreach (JProperty property in style.Properties())
            cssVals.Add(property.Name + ":" + property.Value.ToString() + ";");

        if (cssVals.Any())
            attrs.Add("style=\"" + string.Join(" ", cssVals) + "\"");
        }
            
        return new MvcHtmlString(string.Join(" ", attrs));
    }
}

UmbracoMandatory/Views/Partials/Grid/Bootstrap3.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates
@using Newtonsoft.Json.Linq

@* 
    Razor helpers located at the bottom of this file
*@

@if (Model != null && Model.sections != null)
{
    var oneColumn = ((System.Collections.ICollection)Model.sections).Count == 1;
    
    <div class="umb-grid">
        @if (oneColumn)
        {
            foreach (var section in Model.sections) {
                <div class="grid-section">
                    @foreach (var row in section.rows) {
                        @renderRow(row, true);
                    }
                </div>
            }   
        }else { 
            <div class="container">
                <div class="row clearfix">
                    @foreach (var s in Model.sections) {
                        <div class="grid-section">
                            <div class="col-md-@s.grid column">
                                @foreach (var row in s.rows) {
                                    @renderRow(row, false);
                                }
                            </div>
                        </div>
                    }
                </div>
            </div>   
        }
    </div>
}

@helper renderRow(dynamic row, bool singleColumn){
    <div @RenderElementAttributes(row)>
        @Umbraco.If(singleColumn, "<div class='container'>")
        <div class="row clearfix">
            @foreach ( var area in row.areas ) {
            <div class="col-md-@area.grid column">
                <div @RenderElementAttributes(area)>
                    @foreach (var control in area.controls) {
                        if (control !=null && control.editor != null && control.editor.view != null ) {
                            <text>@Html.Partial("grid/editors/base", (object)control)</text>
                        }
                    }
                </div>
            </div>}
        </div>
        @Umbraco.If(singleColumn, "</div>")
    </div>
}

@functions {
    public static MvcHtmlString RenderElementAttributes(dynamic contentItem)
    {
        var attrs = new List<string>();
        JObject cfg = contentItem.config;

        if(cfg != null)
            foreach (JProperty property in cfg.Properties()) {
                attrs.Add(property.Name + "=\"" + property.Value.ToString() + "\"");
            }
                
        JObject style = contentItem.styles;

        if (style != null) { 
        var cssVals = new List<string>();
        foreach (JProperty property in style.Properties())
            cssVals.Add(property.Name + ":" + property.Value.ToString() + ";");

        if (cssVals.Any())
            attrs.Add("style=\"" + string.Join(" ", cssVals) + "\"");
        }
            
        return new MvcHtmlString(string.Join(" ", attrs));
    }
}

UmbracoMandatory/Views/Partials/Grid/Editors/Base.cshtml
@model dynamic
@using Umbraco.Web.Templates

@functions {
    public static string EditorView(dynamic contentItem)
    {
        string view = contentItem.editor.render != null ? contentItem.editor.render.ToString() : contentItem.editor.view.ToString();
        view = view.ToLower().Replace(".html", ".cshtml");
        
        if (!view.Contains("/")) {
            view = "grid/editors/" + view;
        }

        return view;
    }
}
@try
{
    string editor = EditorView(Model);                                                       
    <text>@Html.Partial(editor, (object)Model)</text>
}
catch (Exception ex) { 
<pre>@ex.ToString()</pre>
}

UmbracoMandatory/Views/Partials/Grid/Editors/Embed.cshtml
@model dynamic
@using Umbraco.Web.Templates
@Html.Raw(Model.value)

UmbracoMandatory/Views/Partials/Grid/Editors/Macro.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates


@if (Model.value != null)
{
    string macroAlias = Model.value.macroAlias.ToString();
    ViewDataDictionary parameters = new ViewDataDictionary();
    foreach (dynamic mpd in Model.value.macroParamsDictionary)
    {
        parameters.Add(mpd.Name, mpd.Value);
    }

    <text>
        @Umbraco.RenderMacro(macroAlias, parameters)
    </text>
}

UmbracoMandatory/Views/Partials/Grid/Editors/Media.cshtml
@model dynamic
@using Umbraco.Web.Templates

@if (Model.value != null)
{   
    var url = Model.value.image;
    if(Model.editor.config != null && Model.editor.config.size != null){
        url += "?width=" + Model.editor.config.size.width;
        url += "&height=" + Model.editor.config.size.height;

        if(Model.value.focalPoint != null){
            url += "&center=" + Model.value.focalPoint.top +"," + Model.value.focalPoint.left;
            url += "&mode=crop";
        }
    }
    
    <img src="@url" alt="@Model.value.altText">
    
    if (Model.value.caption != null)
    {
        <p class="caption">@Model.value.caption</p>
    }
}

UmbracoMandatory/Views/Partials/Grid/Editors/Rte.cshtml
@model dynamic
@using Umbraco.Web.Templates

@Html.Raw(TemplateUtilities.ParseInternalLinks(Model.value.ToString()))

UmbracoMandatory/Views/Sitemap.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "Master.cshtml";
}

@Umbraco.RenderMacro("sitemap")

UmbracoMandatory/Views/TextPage.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "Master.cshtml";
}